[package]
name = "kaichi-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
arrow = { workspace = true }
ndarray = { workspace = true }
statrs = { workspace = true }
rayon = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anndata = { workspace = true }
anndata-hdf5 = { workspace = true }
polars = { workspace = true }
nalgebra-sparse = { workspace = true }

[dev-dependencies]
approx = { workspace = true }
csv = "1"
tempfile = "3"
